import type { HelpArticle } from "./types";

export const ACCOUNT_ARTICLES: HelpArticle[] = [
  {
    slug: "plans-and-pricing",
    title: "Plans and pricing",
    summary: "Free, Essentials and Pro: what each plan includes, and what it costs for your whole company.",
    category: "account",
    keywords: ["price", "cost", "subscription", "free plan", "essentials", "pro", "per user", "seats", "vat", "upgrade"],
    body: [
      { type: "p", text: "Builder OS has three plans. Each is one price for the whole company, not per person, so you can add your office team and site crew without the bill going up. Prices are monthly and exclude VAT." },
      { type: "h", text: "Free: £0" },
      { type: "p", text: "For trying Builder OS on a real job, or a sole trader quoting now and then." },
      {
        type: "list",
        items: [
          "One login: yours. You can invite others, but they can't get in until you choose a plan.",
          "3 new quotes sent a month. Sending an updated version of a quote doesn't count.",
          "A service library of up to 25 items.",
          "Client quote links, comments and online signatures.",
          "Quotes go out in Builder OS's style, without your own logo and colours.",
        ],
      },
      { type: "h", text: "Essentials: £49 a month plus VAT" },
      { type: "p", text: "For quoting, agreeing changes and getting paid. Everything in Free, plus:" },
      {
        type: "list",
        items: [
          "Unlimited quotes and an unlimited service library.",
          "[Bundles](/help/bundles).",
          "Your logo and brand colour on quotes and invoices.",
          "[Variations](/help/variations) with client sign-off.",
          "[Payment plans](/help/payment-plans), [invoices](/help/raising-invoices), [online payments](/help/taking-payments-online) and automatic [payment reminders](/help/payment-reminders).",
        ],
      },
      { type: "h", text: "Pro: £119 a month plus VAT" },
      { type: "p", text: "For running the whole business. Everything in Essentials, plus:" },
      {
        type: "list",
        items: [
          "[Projects](/help/projects), with progress your client can follow in their portal.",
          "The [Team page](/help/team-and-workers): certificates, the weekly schedule and timesheets.",
          "The [site app](/help/site-app) for your team on site.",
          "Job costs: [receipts](/help/expenses-and-receipts), [purchase orders](/help/purchase-orders) and [reports](/help/job-costing-reports).",
          "The sales [pipeline](/help/pipeline), your [web enquiry form](/help/web-enquiry-form) and [online survey booking](/help/online-survey-booking).",
          "[Email automations](/help/automations).",
          "The [calendar](/help/calendar).",
        ],
      },
      { type: "h", text: "How you'll know something isn't on your plan" },
      { type: "p", text: "Areas your plan doesn't include show a small padlock in the sidebar. Open one and you'll see which plan it's on, with a **See plans** button." },
      { type: "tip", text: "New companies get Pro free for 14 days, with no card needed, so you can try everything before you choose. See [Your free trial](/help/free-trial)." },
      { type: "p", text: "To see or change your plan, go to [Settings, Plan & billing](/app/settings/billing). See [Changing your plan](/help/changing-your-plan)." },
    ],
    related: ["free-trial", "changing-your-plan", "welcome"],
  },
  {
    slug: "free-trial",
    title: "Your free trial",
    summary: "Every new company gets Pro free for 14 days, with no card needed. Here's what happens after.",
    category: "account",
    keywords: ["trial", "14 days", "free", "days left", "trial ends", "no card", "expired"],
    body: [
      { type: "p", text: "When you create your company, you get 14 days of Pro for free, with everything switched on. You don't need to give a card to start." },
      { type: "h", text: "During your trial" },
      {
        type: "list",
        items: [
          "Every feature of Pro is open: projects, the site app, the pipeline, job costs, the calendar and the rest.",
          "The top bar shows how many days you have left, for example \"Pro trial: 9 days left\". Click it to choose a plan.",
          "[Settings, Plan & billing](/app/settings/billing) shows the same, and is highlighted when you're down to the last three days.",
        ],
      },
      { type: "tip", text: "Make the most of it: invite your team, put a real job through from quote to invoice, and try the site app on a phone. The [getting-started guide](/help/getting-started-guide) walks you through it." },
      { type: "h", text: "Choosing a plan before it ends" },
      {
        type: "steps",
        items: [
          "Go to [Settings, Plan & billing](/app/settings/billing).",
          "Click **Choose Essentials** or **Choose Pro**.",
          "Enter your card and billing details on the secure payment page, then confirm.",
          "You come back to Plan & billing, showing your new plan.",
        ],
      },
      { type: "p", text: "Only an Admin can choose a plan." },
      { type: "h", text: "If the trial ends without a plan" },
      { type: "p", text: "Your company moves to the Free plan. Nothing is deleted. Areas that Free doesn't include, such as projects or invoices, show a padlock, and opening one shows which plan it needs. Choose a plan at any time and they open again, with everything as you left it." },
      { type: "note", text: "On Free you can send 3 new quotes a month and keep up to 25 items in your library. See [Plans and pricing](/help/plans-and-pricing)." },
    ],
    related: ["plans-and-pricing", "changing-your-plan", "getting-started-guide"],
  },
  {
    slug: "changing-your-plan",
    title: "Changing your plan",
    summary: "Upgrade, switch plans, update your card or cancel from Settings, Plan & billing.",
    category: "account",
    who: "Admins",
    keywords: ["upgrade", "downgrade", "cancel", "switch plan", "card", "billing", "payment failed", "invoice", "receipt", "manage billing"],
    body: [
      { type: "p", text: "You can move between Free, Essentials and Pro whenever you need to. Everything to do with your plan lives on one page: [Settings, Plan & billing](/app/settings/billing)." },
      { type: "h", text: "Choosing a plan for the first time" },
      {
        type: "steps",
        items: [
          "Go to [Settings, Plan & billing](/app/settings/billing).",
          "Click **Choose Essentials** or **Choose Pro** on the plan you want.",
          "Fill in your card and billing address on the secure payment page. You can add your VAT number, and a promotion code if you have one.",
          "Confirm. You're brought back to Plan & billing with your new plan in place.",
        ],
      },
      { type: "h", text: "Switching, updating your card or cancelling" },
      { type: "p", text: "Once you're paying, click **Manage billing** (or **Switch to Pro** or **Switch to Essentials** on a plan card). This opens your billing page, where you can:" },
      {
        type: "list",
        items: [
          "Switch between Essentials and Pro.",
          "Change the card you pay with.",
          "Download your past invoices.",
          "Cancel your plan.",
        ],
      },
      { type: "p", text: "If you cancel, your plan carries on until the end of the period you've paid for. Plan & billing shows the date it ends, then your company moves to Free. Changed your mind? Use **Manage billing** before then." },
      { type: "h", text: "If a payment fails" },
      { type: "p", text: "The top bar shows **Payment failed · Update your card**. You keep your plan for a short while as the payment is retried. Click it, then **Manage billing**, and update your card to keep everything running." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Only Admins can change the plan. Everyone else can see the Plan & billing page, but its buttons are greyed out for them.",
          "Moving to a smaller plan never deletes anything. Areas the plan doesn't include are locked, and open again if you upgrade.",
          "Prices are per company, not per person, and exclude VAT.",
        ],
      },
    ],
    related: ["plans-and-pricing", "free-trial", "company-settings"],
  },
  {
    slug: "company-settings",
    title: "Company settings",
    summary: "What's in Settings: your company details, payments, plan, team, and the getting-started guide.",
    category: "account",
    who: "Admins can change settings; other office roles can view them",
    keywords: ["settings", "company", "branding", "logo", "vat", "markup", "terms", "portal sign-in", "client login"],
    body: [
      { type: "p", text: "Settings is where you look after the company itself: how you appear to clients, how you get paid, your plan and your team. Open it from the cog next to your name at the bottom of the sidebar." },
      { type: "h", text: "The settings pages" },
      {
        type: "list",
        items: [
          "**Company:** your name, VAT number, logo, brand colour, default markup and VAT, and quote terms. See [Setting up your company](/help/setting-up-your-company).",
          "**Payments:** your bank details, payment terms, reminders and online payments. See [Bank details and payment terms](/help/bank-details-and-payment-terms).",
          "**Plan & billing:** your plan and how you pay for it. See [Changing your plan](/help/changing-your-plan).",
          "**Team:** invite people and choose their roles. See [Logins and roles](/help/logins-and-roles).",
          "**Getting started:** your checklist, and the switch to replay the tour. See [Your getting-started guide](/help/getting-started-guide).",
        ],
      },
      { type: "h", text: "Client portal sign-in" },
      { type: "p", text: "Also on the Company page is **Ask clients to confirm their email (recommended)**. With it on, the first time a client opens their portal on a new phone or computer, they're emailed a 6-digit code. That device is then remembered for 90 days. It means a forwarded link on its own isn't enough to see their quotes and invoices. See [Portal sign-in](/help/portal-sign-in)." },
      { type: "p", text: "The same panel shows the address where clients can always find their portal. It's worth putting on your website as \"Client login\"." },
      { type: "h", text: "Your data" },
      { type: "p", text: "At the bottom of the Company page, **Export all data** downloads everything your company keeps in Builder OS. See [Exporting your data](/help/exporting-your-data)." },
      { type: "h", text: "Who can do what" },
      {
        type: "list",
        items: [
          "Only an **Admin** can change company settings, upload a logo, turn portal sign-in on or off, export all data or change the plan.",
          "The office, estimators and site leads can open Settings and see what's there, but can't change it.",
          "Employees use the site app only, so they don't see Settings.",
        ],
      },
      { type: "tip", text: "Changes to your details and terms apply to new quotes. Quotes you've already sent keep exactly what the client saw." },
    ],
    related: ["setting-up-your-company", "bank-details-and-payment-terms", "logins-and-roles", "portal-sign-in"],
  },
  {
    slug: "exporting-your-data",
    title: "Exporting your data",
    summary: "Download everything your company keeps in Builder OS, or everything about one client.",
    category: "account",
    keywords: ["export", "download", "backup", "gdpr", "subject access request", "data request", "csv", "spreadsheet", "leave", "cancel"],
    body: [
      { type: "p", text: "Your data is yours. You can download all of it at any time, and you can download everything held about one client when they ask for a copy of their data." },
      { type: "h", text: "Exporting everything" },
      {
        type: "steps",
        items: [
          "Go to [Settings](/app/settings). You land on **Company**.",
          "Scroll to **Your data** at the bottom.",
          "Click **Export all data**. A ZIP file downloads.",
        ],
      },
      { type: "p", text: "This covers clients, leads, quotes, invoices, projects, your team and more. Only an Admin can export all of the company's data, and you can do it up to five times an hour." },
      { type: "h", text: "Exporting one client's data" },
      { type: "p", text: "Under UK GDPR, a client can ask what you hold about them (a subject access request). To answer it:" },
      {
        type: "steps",
        items: [
          "Open the client from [Clients](/app/clients).",
          "Click **Export data**, next to the date they were added.",
          "Send them the ZIP file, or the parts they asked for.",
        ],
      },
      { type: "p", text: "It includes their client record, their quotes and everything attached to them, invoices, variations, projects, what they did in the portal, any leads with their email address, and survey bookings. Admins, the office and estimators can do this." },
      { type: "h", text: "What's in the ZIP" },
      {
        type: "list",
        items: [
          "**README.txt:** what's in the file and how many rows each part has.",
          "**data.json:** everything in one file.",
          "**A csv folder:** the same information split into one spreadsheet file per type of record, ready to open in Excel or Google Sheets.",
        ],
      },
      { type: "note", text: "Photos, documents and receipt images aren't inside the ZIP. They're listed, and you can download them from the app. Sign-in codes and other security details are always left out." },
      { type: "tip", text: "Thinking of moving on? Export everything before you cancel. Nothing locks you in." },
    ],
    related: ["privacy-and-security", "clients", "company-settings"],
  },
  {
    slug: "privacy-and-security",
    title: "Privacy and security",
    summary: "How Builder OS keeps your company's and your clients' information safe, and what you control.",
    category: "account",
    keywords: ["privacy", "security", "gdpr", "safe", "cookies", "data protection", "roles", "spam", "card details", "delete"],
    body: [
      { type: "p", text: "You keep a lot of personal details in Builder OS: clients' names, addresses and phone numbers, your team's certificates and timesheets. Here's how that information is looked after, and the settings that are in your hands." },
      { type: "h", text: "Your company's data is kept apart" },
      { type: "p", text: "Each company's information is kept separate from every other company's, so nobody outside your company can see your clients, prices or jobs. Information is encrypted while it's sent and while it's stored." },
      { type: "h", text: "People see only what their role needs" },
      { type: "p", text: "Everyone has their own login and a role: Admin, Office, Estimator, Site lead or Employee. Site leads and employees never see prices, costs or margins. See [Logins and roles](/help/logins-and-roles)." },
      { type: "h", text: "Protecting your clients' portal" },
      {
        type: "list",
        items: [
          "Turn on **Ask clients to confirm their email** in [Settings](/app/settings), so a forwarded link on its own can't open a client's portal. See [Portal sign-in](/help/portal-sign-in).",
          "If a portal link went to the wrong person, open the client and use **Reset link**. The old link stops working straight away.",
          "**Sign out everywhere** on the client's page signs them out of every device. They'll need a new code to get back in.",
        ],
      },
      { type: "h", text: "Payments" },
      { type: "p", text: "Card details go straight to Stripe, the payment provider, whether it's you paying for Builder OS or your client paying an invoice. Builder OS never sees or stores them. Money from your clients goes to your own Stripe account." },
      { type: "h", text: "Your website forms" },
      { type: "p", text: "Your enquiry form and survey booking page are protected from spam and automated sign-ups without asking your clients to solve a puzzle." },
      { type: "h", text: "Cookies" },
      { type: "p", text: "Builder OS only uses the cookies it needs to work, such as keeping you signed in and remembering a client's device. There are no advertising or tracking cookies." },
      { type: "h", text: "Your clients' rights" },
      { type: "p", text: "For your clients' details, your company is in charge of the data and Builder OS looks after it for you. If a client asks for a copy of what you hold, you can [export their data](/help/exporting-your-data) from their page in a click. A client with no quotes can be deleted from their page; one with quotes can be archived instead, which hides them and keeps your records." },
      { type: "note", text: "For the full detail, including how long information is kept and how to close your account, read the Privacy policy and Cookie policy on the Builder OS website." },
    ],
    related: ["exporting-your-data", "logins-and-roles", "portal-sign-in", "company-settings"],
  },
];
