import type { HelpArticle } from "./types";

export const GETTING_STARTED_ARTICLES: HelpArticle[] = [
  {
    slug: "welcome",
    title: "Welcome to Builder OS",
    summary: "What Builder OS does, from the first enquiry to the final payment, and where to read more.",
    category: "getting-started",
    keywords: ["overview", "introduction", "what is", "how it works", "start here", "tour"],
    body: [
      { type: "p", text: "Builder OS runs the paperwork side of a building or renovation firm in one place. It follows a job the way work really flows: an enquiry comes in, you quote it, the client signs, you run the job, and you get paid." },
      { type: "h", text: "From enquiry to paid, step by step" },
      {
        type: "steps",
        items: [
          "**A lead comes in.** Someone rings about a kitchen extension, or fills in the form on your website. It lands in your [pipeline](/help/pipeline) so it never goes cold. See [Leads](/help/leads) and [Your web enquiry form](/help/web-enquiry-form).",
          "**You quote it.** Build the quote from your own prices in the [service library](/help/service-library), with sections like Kitchen and Bathroom, and see your margin as you go. See [Building a quote](/help/building-a-quote).",
          "**You send it.** The client gets a private link to a clean, branded quote they can read on their phone, and you hear when they open it. See [Sending a quote](/help/sending-a-quote).",
          "**The client signs.** They accept online with a typed signature, so there's a clear record of what was agreed. See [Accepted quotes and signatures](/help/accepted-quotes-and-signatures).",
          "**You run the job.** Turn the accepted quote into a [project](/help/projects) with stages, tasks, a site diary and files. Your team sees their jobs in the [site app](/help/site-app), and extra work is priced as a [variation](/help/variations).",
          "**You raise invoices.** The deposit and stage payments you agreed in the [payment plan](/help/payment-plans) become invoices in a click. See [Raising invoices](/help/raising-invoices).",
          "**You get paid.** Clients pay by bank transfer, or by card and bank online if you [take payments online](/help/taking-payments-online). Polite [reminders](/help/payment-reminders) chase late payers for you.",
        ],
      },
      { type: "h", text: "Everything else that helps" },
      {
        type: "list",
        items: [
          "**Clients:** every client has a [portal](/help/client-portal) where they see their quotes, invoices and, if you choose, the progress of their job.",
          "**Your team:** keep everyone who works for you, their [certificates](/help/certificates), the [weekly schedule](/help/weekly-schedule) and [timesheets](/help/timesheets-and-check-ins) on the [Team page](/help/team-and-workers).",
          "**Job costs:** log [receipts](/help/expenses-and-receipts) and [purchase orders](/help/purchase-orders) against each job, then see what it really made in [job costing reports](/help/job-costing-reports).",
          "**Winning more work:** [follow-ups](/help/follow-ups), [online survey booking](/help/online-survey-booking) and [email automations](/help/automations) keep enquiries moving.",
        ],
      },
      { type: "h", text: "Where to start" },
      { type: "p", text: "The **Getting started** checklist in the top bar walks you through all of this in short chapters, and ticks steps off as you do them. Begin with [Setting up your company](/help/setting-up-your-company), then take the two-minute tour described in [Finding your way around](/help/finding-your-way-around)." },
      { type: "note", text: "Some features need a paid plan. New companies get Pro free for 14 days, so you can try everything first. See [Plans and pricing](/help/plans-and-pricing)." },
    ],
    related: ["setting-up-your-company", "finding-your-way-around", "getting-started-guide", "plans-and-pricing"],
  },
  {
    slug: "setting-up-your-company",
    title: "Setting up your company",
    summary: "Create your company, then add your details, logo and quote terms so every quote looks right.",
    category: "getting-started",
    who: "Admins",
    keywords: ["sign up", "create account", "company details", "logo", "vat number", "trading name", "terms", "brand colour", "first steps"],
    body: [
      { type: "p", text: "Before you send your first quote, spend ten minutes on your company details. Your name, VAT number, logo and terms go on every quote and invoice, so you only type them once." },
      { type: "h", text: "Creating your company" },
      { type: "p", text: "When you create your account, you're asked to create your company (or choose one, if someone invited you). The person who creates the company becomes its **Admin**. Your company starts on a free 14-day trial of Pro, with no card needed." },
      { type: "p", text: "If you work for more than one company, you can switch between them with the company name at the top of the sidebar." },
      { type: "h", text: "Step by step" },
      {
        type: "steps",
        items: [
          "Click the cog next to your name at the bottom of the sidebar, or go to [Settings](/app/settings). You land on **Company**.",
          "Fill in your **Company name**. Add a **Trading name** if you trade under a different name, and your **VAT number** if you're VAT registered (leave it blank if not).",
          "Under **Branding**, click **Upload logo** and pick your logo (PNG, JPEG or WebP, up to 1 MB). A wide logo on a transparent background looks best. If you see a **Logo link** box instead, paste a link to your logo.",
          "Set your **Brand colour**, used for accents on your quotes, invoices and client emails.",
          "Under **Quote defaults**, set your **Default markup** and **Default VAT rate** (20% standard, 5% reduced or 0%).",
          "Paste your **Quote terms**: payment terms, how long the quote is valid, and what's excluded. They're printed at the end of every quote.",
          "Click **Save changes**.",
        ],
      },
      { type: "tip", text: "Markup and VAT here are only starting points. You can change them on each quote and on each line, for example 5% VAT on a qualifying job." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Only an Admin can change company settings. Others can open the page but can't edit it.",
          "Your own logo and colours on quotes and invoices need the Essentials or Pro plan. On Free, quotes go out in Builder OS's style.",
          "Changes apply to new quotes. Quotes you've already sent keep what the client saw.",
        ],
      },
      { type: "h", text: "What to do next" },
      { type: "p", text: "Add your [bank details and payment terms](/help/bank-details-and-payment-terms) so invoices show where to pay, [invite your team](/help/logins-and-roles), and fill your [service library](/help/service-library) with the things you price most." },
    ],
    related: ["company-settings", "bank-details-and-payment-terms", "logins-and-roles", "service-library"],
  },
  {
    slug: "finding-your-way-around",
    title: "Finding your way around",
    summary: "The sidebar, top bar and shortcuts, and the quick tour that shows you where everything lives.",
    category: "getting-started",
    keywords: ["sidebar", "menu", "navigation", "tour", "dashboard", "top bar", "lock", "mobile", "phone"],
    body: [
      { type: "p", text: "Builder OS is laid out in the order work flows: from enquiry, to quote, to job, to money. Once you know the sidebar and the top bar, you can get anywhere in a click or two." },
      { type: "h", text: "The sidebar" },
      { type: "p", text: "Every area of the business is on the left:" },
      {
        type: "list",
        items: [
          "**Dashboard:** quotes awaiting a reply, what you've won this month, money owed and follow-ups due.",
          "**Pipeline:** your enquiries and leads.",
          "**Quotes** and the **Service library** of your prices.",
          "**Variations:** extra work and changes, priced and approved.",
          "**Projects** and the **Calendar**.",
          "**Payments:** invoices and money in.",
          "**Purchases:** receipts, expenses and purchase orders.",
          "**Clients**, **Team** and **Reports**.",
        ],
      },
      { type: "p", text: "A small padlock next to an item means your plan doesn't include it. Click it to see which plan does. Under **Portals** there's a link to the **Site app** your team uses on their phones." },
      { type: "p", text: "At the bottom is your name and role. Click your picture to manage your profile or sign out, and the cog to open Settings." },
      { type: "h", text: "The top bar" },
      {
        type: "list",
        items: [
          "**Getting started:** your checklist, with how far you've got. See [Your getting-started guide](/help/getting-started-guide).",
          "**The bell:** your [notifications](/help/notifications).",
          "**+ New:** start a quote, lead, client or job from any screen. See [Search and the New menu](/help/search-and-new-menu).",
        ],
      },
      { type: "p", text: "During your trial, the top bar also shows how many days are left, with a link to choose a plan." },
      { type: "h", text: "Take the tour" },
      { type: "p", text: "The first time you open the dashboard, a short tour points out each of these. It's six stops and takes about a minute. Click **Show me round** to start, **Next** and **Back** to move, or **Not now** to skip it." },
      { type: "p", text: "To watch it again, go to [Settings, Getting started](/app/settings/getting-started) and click **Replay the tour**." },
      { type: "h", text: "On your phone" },
      { type: "p", text: "On a phone or small tablet, the sidebar is tucked away. Tap the menu button at the top left to open it." },
      { type: "tip", text: "Press ⌘K on a Mac, or Ctrl K on Windows, from any page to search for a client, quote or job, or jump straight to a page." },
    ],
    related: ["search-and-new-menu", "getting-started-guide", "notifications", "welcome"],
  },
  {
    slug: "getting-started-guide",
    title: "Your getting-started guide",
    summary: "A checklist in short chapters that takes you from setting up to your first paid invoice.",
    category: "getting-started",
    keywords: ["checklist", "onboarding", "guide", "chapters", "levels", "progress", "skip", "hide checklist", "replay tour"],
    body: [
      { type: "p", text: "The getting-started guide is a checklist that walks you through Builder OS in short chapters. Steps tick themselves off as you and your team actually do things, like sending a quote or raising an invoice, so it's never out of step." },
      { type: "h", text: "Opening it" },
      {
        type: "list",
        items: [
          "Click the **Getting started** pill in the top bar. It shows how far you've got as a percentage.",
          "On the dashboard, the getting-started card shows your next step. Click **See all steps** to open the full list.",
          "Any time, go to [Settings, Getting started](/app/settings/getting-started).",
        ],
      },
      { type: "h", text: "The chapters" },
      {
        type: "list",
        items: [
          "**Find your way around:** the two-minute tour.",
          "**Set up your company:** your details, logo, bank details and team.",
          "**Price your work:** your service library and bundles.",
          "**Quote and win:** build, send and get a quote signed.",
          "**Get paid:** payment plans, invoices and online payments.",
          "**Run the job:** projects, the site app, variations and job costs.",
          "**Win more work:** leads, your web form, survey booking and follow-up emails.",
        ],
      },
      { type: "p", text: "Each chapter is a level, so you'll see something like \"Level 3 of 7\". Open a step to see why it matters and how it works, with a button that takes you straight to the right page. **Up next** at the top always points at the next thing to do." },
      { type: "h", text: "Steps that don't apply to you" },
      { type: "p", text: "Don't do online booking? Click **Skip, not for us** on that step. A skipped step counts as done. Changed your mind? Click **Put it back**, or use **Bring back skipped steps** on the Getting started settings page." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Everyone sees a guide that fits their role. Steps your role can't do are left out, so an estimator won't be asked to add bank details.",
          "Steps your plan doesn't include are shown locked, with a **See plans** button, and don't count towards your progress.",
          "When you finish a chapter, you get a short well done note.",
        ],
      },
      { type: "h", text: "Hiding it" },
      { type: "p", text: "Once you know your way around, click **Hide the checklist** at the bottom of the guide (or the cross on the dashboard card). To bring it back, go to [Settings, Getting started](/app/settings/getting-started) and click **Show the checklist in the top bar**. The same page has **Replay the tour**." },
    ],
    related: ["welcome", "finding-your-way-around", "setting-up-your-company"],
  },
  {
    slug: "notifications",
    title: "Notifications",
    summary: "The bell tells you when a client opens or signs a quote, an enquiry arrives, or an invoice is paid.",
    category: "getting-started",
    keywords: ["bell", "alerts", "unread", "mark all read", "quote opened", "signed", "enquiry", "paid"],
    body: [
      { type: "p", text: "The bell in the top bar is where Builder OS tells you about things that need your attention, like a client opening your quote or a new enquiry. Each notification links straight to the quote, lead or job it's about." },
      { type: "h", text: "What you'll hear about" },
      {
        type: "list",
        items: [
          "**Quotes:** when a client first opens a version of your quote, leaves a comment or question, accepts or declines it. These go to whoever sent the quote (or to the Admins, if that person has left).",
          "**Variations:** when a client approves or rejects a variation. Same people as for quotes.",
          "**New enquiries** from your website form go to Admins and the office.",
          "**Leads:** when a lead is given to you.",
          "**Survey visits:** when a visit is booked or cancelled, the surveyor hears about it.",
          "**Tasks:** when you're given a task on a job (if you have a login).",
          "**Receipts** logged from the site app go to Admins and the office.",
          "**Certificates** that have expired or expire in the next 30 days go to Admins and the office.",
          "**Invoices paid online** go to Admins and the office.",
        ],
      },
      { type: "p", text: "You won't get a notification for something you did yourself." },
      { type: "h", text: "Reading them" },
      {
        type: "steps",
        items: [
          "A number on the bell shows how many you haven't read.",
          "Click the bell to see your latest notifications, newest first. Unread ones are in bold with a dot.",
          "Click one to go straight to it. It's marked as read.",
          "Click **Mark all read** to clear the number in one go.",
        ],
      },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "The bell checks for new notifications every minute while Builder OS is open, and straight away when you click it.",
          "It shows your 30 most recent. Notifications older than 90 days are cleared out.",
          "Notifications are personal: each person sees only their own.",
          "The site app has the same bell, so site staff hear about tasks given to them.",
          "Emails still go out as before, for example when a client accepts a quote. The bell is the in-app copy.",
        ],
      },
      { type: "tip", text: "When a client opens your quote, it's a good moment to give them a ring while it's fresh in their mind." },
    ],
    related: ["finding-your-way-around", "sending-a-quote", "client-comments-and-questions", "leads"],
  },
  {
    slug: "search-and-new-menu",
    title: "Search and the New menu",
    summary: "Find any client, quote, job or invoice with ⌘K, and start something new from any screen.",
    category: "getting-started",
    keywords: ["search", "find", "command k", "ctrl k", "shortcut", "new", "quick", "jump to"],
    body: [
      { type: "p", text: "Two shortcuts save a lot of clicking: search, to find anything by name, address or number, and the **+ New** button, to start a quote, lead or job from whichever screen you're on." },
      { type: "h", text: "Searching" },
      {
        type: "steps",
        items: [
          "Press **⌘K** on a Mac or **Ctrl K** on Windows, or click **Search** at the top of the sidebar.",
          "Start typing a name, part of an address or a postcode. Results appear as you type.",
          "Use the up and down arrows to move, and Enter to open. Press Esc to close.",
        ],
      },
      { type: "p", text: "Search finds clients, leads, quotes, projects, invoices, people on your team and purchase orders. You'll see a few of the best matches of each kind." },
      { type: "tip", text: "Know the number? Type it. \"Q-12\" finds quote 12, \"INV 7\" finds invoice 7 and \"PO-0003\" finds a purchase order. A bare number works too." },
      { type: "p", text: "Below the results, search also offers shortcuts: **Start something** (like New quote) and **Go to** (like Calendar, Projects or Settings). Type \"calendar\" or \"settings\" and press Enter to jump there." },
      { type: "h", text: "The + New menu" },
      { type: "p", text: "Click **New** at the top right of any screen. Depending on your role and plan, you can start:" },
      {
        type: "list",
        items: [
          "**New quote**",
          "**New lead** (Pro)",
          "**New client**",
          "**New project** (Pro)",
          "**New purchase order** (Pro)",
          "**Add someone to the team** (Pro)",
        ],
      },
      { type: "h", text: "Good to know" },
      { type: "p", text: "Search and the New menu only offer what you're allowed to see and do. A site lead won't find invoices or be offered New quote, and shortcuts to pages your plan doesn't include are left out. See [Logins and roles](/help/logins-and-roles)." },
    ],
    related: ["finding-your-way-around", "building-a-quote", "leads", "logins-and-roles"],
  },
  {
    slug: "calendar",
    title: "The calendar",
    summary: "Survey visits, task dates and jobs starting or finishing, on one calendar by month or week.",
    category: "getting-started",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["diary", "schedule", "month", "week", "surveys", "visits", "tasks", "who's doing what"],
    body: [
      { type: "p", text: "The calendar shows who's doing what, and when, across all your jobs. It saves you piecing it together from each project and lead." },
      { type: "h", text: "What's on it" },
      {
        type: "list",
        items: [
          "**Surveys:** site visits booked with leads, with the time, the type of job and the postcode.",
          "**Job starts and finishes:** the start date of each project, and the date it's due to finish (until it's marked complete).",
          "**Tasks:** project tasks on their dates, with a dot showing their status. A task spread over several days shows \"Starts:\" on its first day and \"Due:\" on its last. Finished tasks are crossed out.",
        ],
      },
      { type: "p", text: "Everything comes from your projects and pipeline, so there's nothing extra to keep up to date. Click anything on the calendar to open the lead or project it belongs to." },
      { type: "h", text: "Getting around" },
      {
        type: "steps",
        items: [
          "Open [Calendar](/app/calendar) from the sidebar. It opens on this month.",
          "Use the arrows to go back or forward, and **Today** to come back.",
          "Switch between **Month** and **Week**. Week view shows every item with its job and person.",
          "In month view, click a date (or \"+ more\" on a busy day) to see that week in full.",
        ],
      },
      { type: "h", text: "One person's tasks" },
      { type: "p", text: "Use the drop-down at the top to choose a person, for example \"Dave's tasks\". The calendar then shows only their tasks, without surveys or job dates. Choose **Everyone and everything** to see it all again." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "To add or move something, change it where it lives: set task dates on the [project](/help/project-stages-and-tasks), and book visits on the [lead](/help/online-survey-booking).",
          "Site leads see tasks and job dates but not surveys, since they don't use the pipeline.",
          "Lost leads don't appear.",
        ],
      },
    ],
    related: ["project-board-and-timeline", "project-stages-and-tasks", "online-survey-booking", "weekly-schedule"],
  },
];
