import type { HelpArticle } from "./types";

export const PROJECT_ARTICLES: HelpArticle[] = [
  {
    slug: "projects",
    title: "Projects: running the job once it's won",
    summary: "Turn an accepted quote into a project with stages, tasks, a site diary and files, all in one place.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["job", "start project", "new project", "booked in", "on site", "snagging", "handover", "status"],
    body: [
      { type: "p", text: "A project is where you run a job day to day, from booked in to handover. It keeps the stages, tasks, site diary and files for one job together, so everyone knows where things stand." },
      { type: "h", text: "Start a project from an accepted quote" },
      { type: "p", text: "This is the quickest way, because the work you priced becomes the plan." },
      {
        type: "steps",
        items: [
          "Open the accepted quote and click **Start project**.",
          "Leave **Turn each quote line into a task** ticked if you want a task for every line. Untick it to start with empty stages.",
          "Add a **Start on site** date if you know it. You can set it later.",
          "Click **Start project**. Each section of the quote becomes a stage, and you land on the new project.",
        ],
      },
      { type: "p", text: "The project takes its name from the quote's title, and the site address from the quote (or the client's address if the quote has none). Each quote can have one project. Once it exists, the quote shows **Open project** instead." },
      { type: "h", text: "Start one from scratch" },
      { type: "p", text: "For repairs, day-rate work or a job priced elsewhere, go to [Projects](/app/projects) and click **New project**. Give it a name (for example \"Bathroom refit, 14 Elm Road\"), choose the client, then click **Create project**." },
      { type: "h", text: "The project's details" },
      {
        type: "list",
        items: [
          "**Status**: Booked in, On site, Snagging, Complete or On hold. Change it from the coloured label next to the project name.",
          "**Start on site** and **Planned finish** dates.",
          "**Runs the job**: usually the site lead. The job shows on their dashboard.",
          "**Site address**: fill it in, or click the **Use ...'s address** link (it shows your client's name) to copy theirs across.",
          "**Show progress in the client's portal**: on by default. See [Sharing progress with clients](/help/sharing-progress-with-clients).",
        ],
      },
      { type: "p", text: "To change any of these later, click **Details** at the top of the project." },
      { type: "h", text: "Finding your jobs" },
      { type: "p", text: "The Projects page shows **Current**, **Complete** or **All** jobs. Each card shows the client, progress (tasks done out of the total), dates, who runs it, and any late or waiting tasks." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Each project has tabs: Overview, Board, List, Timeline, Site diary, Files and (for people who see prices) Costs.",
          "On a project started from a quote, the Overview shows the money: contract value, invoiced, paid and still to invoice. Only people who can see prices get this.",
          "Site leads can run projects but never see prices or margins.",
          "Only Admins and the office can delete a project. Deleting removes its tasks, diary and files for good (the quote and invoices stay). Usually it's better to mark it Complete.",
        ],
      },
      { type: "tip", text: "Set the status to On site when work starts and Snagging when you're on the finishing list. Your client sees the status in their portal too." },
    ],
    related: ["project-stages-and-tasks", "project-board-and-timeline", "site-diary", "accepted-quotes-and-signatures", "job-costing-reports"],
  },
  {
    slug: "project-stages-and-tasks",
    title: "Stages and tasks",
    summary: "Break a job into stages and tasks, give each task a person and dates, and tick them off as you go.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["task", "stage", "phase", "checklist", "assign", "waiting", "late", "list view", "trade"],
    body: [
      { type: "p", text: "Stages are the big chunks of a job, like Groundworks, First fix or Decorating. Tasks are the jobs inside them. Together they show exactly how far along you are, and what's slipping." },
      { type: "h", text: "Working with stages" },
      { type: "p", text: "Open a project and click the **List** tab. Tasks are grouped by stage, each with its own progress bar." },
      {
        type: "list",
        items: [
          "Click **Add stage** at the bottom to add one, for example \"Second fix\" or \"Snagging\".",
          "Use the **...** button on a stage to **Rename**, **Move up**, **Move down** or **Delete stage**.",
          "Deleting a stage keeps its tasks. They move to **No stage**.",
        ],
      },
      { type: "h", text: "Adding a task" },
      { type: "p", text: "For a quick task, type into the **Add a task to...** box under a stage and press Enter. For the full details, click **New task**." },
      {
        type: "steps",
        items: [
          "Fill in **What needs doing**, for example \"First fix electrics, kitchen\".",
          "Choose the **Stage** and **Status**.",
          "Pick **Who's doing it** from your team, or leave it as Nobody yet.",
          "Add a **Trade** if it helps, such as Electrician. This is handy for a firm that isn't on your team.",
          "Set **Start** and **Due** dates so the task shows on the timeline and the week's plan.",
          "Add **Notes** if needed, then click **Add task**.",
        ],
      },
      { type: "h", text: "Task statuses" },
      {
        type: "list",
        items: [
          "**To do**: not started.",
          "**In progress**: under way.",
          "**Waiting**: held up by materials, another trade, the client or a decision. Use the notes to say what.",
          "**Done**: finished.",
        ],
      },
      { type: "p", text: "A task is **late** when its due date has passed and it isn't done. Late tasks show in red, and the Board tab shows how many there are." },
      { type: "h", text: "Ticking things off" },
      { type: "p", text: "In the List tab, tick the box next to a task to mark it done, or change its status from the drop-down. Tick **Hide finished tasks** to see only what's left. Click any task to change its details or delete it." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "When you give a task to someone with a login, they get a notification and it appears in their [site app](/help/site-app).",
          "People on site can start tasks, mark them done or say what they're waiting for from their phone. A waiting reason is added to the task's notes with the date.",
          "Your client never sees the task list or notes. Their portal only shows how far each stage is.",
        ],
      },
      { type: "tip", text: "Started from a quote with lots of small lines? Delete the ones you don't need, or rename them, so the list matches how your team actually works." },
    ],
    related: ["projects", "project-board-and-timeline", "weekly-schedule", "site-app"],
  },
  {
    slug: "project-board-and-timeline",
    title: "The board, timeline and overview",
    summary: "See a job's tasks as columns, as a week-by-week timeline, or at a glance on the overview.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["board", "kanban", "timeline", "gantt", "schedule", "overview", "drag", "coming up", "needs attention"],
    body: [
      { type: "p", text: "The same tasks can be seen in different ways. The board is great for daily juggling, the timeline for planning who's on site when, and the overview for a quick check on how the job is going." },
      { type: "h", text: "Overview" },
      { type: "p", text: "The first tab on every project. It shows:" },
      {
        type: "list",
        items: [
          "**Progress**: tasks done out of the total, plus a bar for each stage.",
          "**Needs attention**: late tasks and anything waiting.",
          "**Coming up this week**: tasks starting or due in the next 7 days.",
          "**Latest from site**: the newest site diary entries.",
          "**Money** (for people who see prices, on projects started from a quote): quote accepted, approved variations, contract value, invoiced, paid and still to invoice.",
          "Whether the client can follow progress in their portal.",
        ],
      },
      { type: "h", text: "Board" },
      { type: "p", text: "The **Board** tab shows four columns: To do, In progress, Waiting and Done. Each card shows the task, its stage, who's doing it and its due date, with late ones in red." },
      {
        type: "list",
        items: [
          "Drag a card to another column to change its status, or drag it up and down to reorder.",
          "Click a card to open and change it.",
          "Type into the box at the bottom of a column to add a task straight into it.",
        ],
      },
      { type: "tip", text: "On a phone or tablet, dragging can be fiddly. Open the card and change its status instead." },
      { type: "h", text: "Timeline" },
      { type: "p", text: "The **Timeline** tab lays out tasks week by week, grouped by stage, with today marked. Bars are coloured by status (To do, In progress, Waiting, Done), so you can spot overlaps and slipping work. Tasks without dates are listed underneath so you can schedule them." },
      { type: "p", text: "Click any bar to change its dates. A task needs a start or due date to appear on the timeline." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Changes show straight away and save in the background. If something goes wrong, you'll see a message at the top.",
          "Task dates also feed the team's [weekly schedule](/help/weekly-schedule), so planning here plans your people too.",
        ],
      },
    ],
    related: ["project-stages-and-tasks", "projects", "weekly-schedule"],
  },
  {
    slug: "site-diary",
    title: "The site diary",
    summary: "Keep a dated record of each day on site, with weather and photos, and choose which updates the client sees.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads (anyone on the job can post from the site app)",
    keywords: ["diary", "log", "daily report", "photos", "weather", "site update", "progress photos"],
    body: [
      { type: "p", text: "The site diary is a running record of the job: who was there, deliveries, problems, decisions and photos. It's useful for keeping everyone up to date, and handy if there's ever a question about what happened and when." },
      { type: "h", text: "Posting an update" },
      {
        type: "steps",
        items: [
          "Open the project and click the **Site diary** tab.",
          "Check the date. It starts as today, and you can pick an earlier day if you're catching up.",
          "Pick the weather if it matters: Dry, Rain, Windy, Cold / frost or Hot.",
          "Write what happened, for example \"Steels delivered and in. Building control visited, happy with the foundations.\"",
          "Click **Photos** to add pictures (up to 12 per entry).",
          "Tick **Share with the client** if you want them to see it, then click **Post update**.",
        ],
      },
      { type: "h", text: "Team only or shared" },
      { type: "p", text: "Every entry is marked **Team only** or **Shared with client**. Click the label on an entry to switch it. Shared entries appear under \"Updates from site\" in the client's portal, with their photos." },
      { type: "note", text: "You can only share entries when the project is set to show progress in the client's portal. Turn this on in the project's **Details**." },
      { type: "h", text: "Updates from site" },
      { type: "p", text: "Anyone working on the job can post an update with photos from the [site app](/help/site-app) on their phone. These arrive in the diary as team only, so the office always decides what reaches the client." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Entries are grouped by day, newest first, with who wrote them.",
          "Photos are made smaller before they upload, so posting from site is quick.",
          "To delete an entry, click the bin icon and click again to confirm. Its photos go too.",
          "The newest entries also show on the project's Overview under **Latest from site**.",
        ],
      },
      { type: "tip", text: "A short update with two or three photos at the end of each day goes a long way. Share the good ones and your client will feel looked after without needing to ring you." },
    ],
    related: ["sharing-progress-with-clients", "site-app", "project-files", "projects"],
  },
  {
    slug: "project-files",
    title: "Project files",
    summary: "Keep drawings, specs and certificates with the job, and share the ones your client needs.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["files", "documents", "drawings", "plans", "specs", "upload", "pdf", "certificates", "warranty"],
    body: [
      { type: "p", text: "The Files tab keeps the paperwork for a job in one place: drawings, specifications, building control letters, electrical certificates and so on. You can share any of them with your client through their portal." },
      { type: "h", text: "Adding files" },
      {
        type: "steps",
        items: [
          "Open the project and click the **Files** tab.",
          "Drag files onto the box, or click **Choose files**.",
          "Wait for the upload to finish. Each file then shows its size, who added it and when.",
        ],
      },
      { type: "p", text: "You can upload PDFs and images (JPEG, PNG or WebP), up to 4 MB each. If a PDF is bigger, compress it or split it into parts and try again." },
      { type: "h", text: "Sharing a file with your client" },
      { type: "p", text: "Every file starts as **Team only**. Click that label to switch it to **Shared**, and your client can open it under \"Documents\" in their portal. Click again to make it team only." },
      { type: "note", text: "Sharing only works when the project shows progress in the client's portal. If the button is greyed out, turn on **Show progress in the client's portal** in the project's **Details** first." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Click a file's name to open it.",
          "To delete a file, click the bin icon, then click again to confirm.",
          "Photos from site are best posted in the [site diary](/help/site-diary), where they sit with the day's notes.",
          "Receipts and supplier invoices belong in the job's costs. See [Expenses and receipts](/help/expenses-and-receipts).",
        ],
      },
      { type: "tip", text: "At handover, share the certificates and warranties the client should keep, like the electrical certificate and boiler paperwork. They'll have them all in one place." },
    ],
    related: ["sharing-progress-with-clients", "site-diary", "client-portal", "expenses-and-receipts"],
  },
  {
    slug: "sharing-progress-with-clients",
    title: "Sharing progress with clients",
    summary: "Let your client follow the job in their portal: stage progress, key dates, and the updates and files you share.",
    category: "projects",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["portal", "client updates", "progress", "share", "visibility", "what the client sees"],
    body: [
      { type: "p", text: "Clients love knowing how their job is going. With progress sharing, they can check their portal any time instead of ringing you to ask." },
      { type: "h", text: "Turning it on or off" },
      { type: "p", text: "Sharing is on for new projects. To check or change it, open the project, click **Details** and tick or untick **Show progress in the client's portal**, then click **Save details**. The project's Overview tells you which way it's set." },
      { type: "h", text: "What your client sees" },
      { type: "p", text: "The project appears on their portal home under \"Your project\". When they open it, they see:" },
      {
        type: "list",
        items: [
          "The project name, its status (for example On site or Snagging), the site address and the start and finish dates.",
          "An overall percentage, and each stage marked Done, In progress or Not started.",
          "**Updates from site**: only the diary entries you've shared, with their photos.",
          "**Documents**: only the files you've shared.",
        ],
      },
      { type: "h", text: "What your client never sees" },
      {
        type: "list",
        items: [
          "The task list, who's doing what, or task notes.",
          "Diary entries and files marked Team only.",
          "Costs, margins or anything about your team.",
        ],
      },
      { type: "h", text: "Sharing updates and files" },
      {
        type: "steps",
        items: [
          "In the **Site diary** tab, tick **Share with the client** before you post, or click **Team only** on an existing entry to share it.",
          "In the **Files** tab, click **Team only** next to a file to change it to **Shared**.",
        ],
      },
      { type: "note", text: "Your client isn't sent an email when you share something. They see it next time they open their portal, so mention it if it's something important." },
      { type: "tip", text: "Updates posted from the site app always start as team only. Have a quick look each evening and share the best ones." },
    ],
    related: ["client-portal", "site-diary", "project-files", "portal-sign-in"],
  },
];
