import type { HelpArticle } from "./types";

export const QUOTE_ARTICLES: HelpArticle[] = [
  {
    slug: "service-library",
    title: "Your service library",
    summary: "Save the work you price often, with your rates, so every quote is quicker and consistent.",
    category: "quotes",
    who: "Admins and Estimators can change it. The office can view it.",
    keywords: ["price list", "rates", "services", "items", "categories", "archive", "templates"],
    body: [
      { type: "p", text: "The service library is your price list inside Builder OS. Add the jobs you price again and again, like a plaster skim per m² or a boiler swap per job, and you can drop them onto any quote in a couple of keystrokes." },
      { type: "h", text: "Adding a service" },
      {
        type: "steps",
        items: [
          "Open **Service library** from the menu and click **New service**.",
          "Give it a **Name** and a **Category** (pick one from the list or type a new one, like 'Bathrooms' or 'Electrical').",
          "Set the **Unit**, which is how it's measured: m², m, item, point, job, day and so on.",
          "Enter the **Rate**. This is your price per unit before markup.",
          "Leave **Markup** blank to use your company default, or type a percentage just for this service.",
          "Add a **Description** if you like. It's shown to the client under the line on a quote.",
          "Click **Add service**.",
        ],
      },
      { type: "p", text: "Under the form you'll see what the client will pay per unit, before VAT, once the markup is added." },
      { type: "h", text: "Finding things" },
      { type: "p", text: "Use the categories down the left, the search box, or the **All**, **Services** and **Bundles** buttons. The most used items come first, and each card shows how many quotes it's been used in." },
      { type: "h", text: "Changing, archiving and deleting" },
      {
        type: "list",
        items: [
          "Open a service to change it, then click **Save changes**. Quotes you've already written keep the price they had.",
          "Changing a rate also reprices any [bundles](/help/bundles) that contain the service.",
          "**Archive** hides a service from the library and from new quotes. You can restore it from **Archived** at any time.",
          "You can only delete a service that isn't on any quote or in a bundle. Otherwise, archive it.",
        ],
      },
      { type: "h", text: "Good to know" },
      { type: "note", text: "On the Free plan the library holds up to 25 services and bundles (archived ones don't count). Essentials and Pro give you an unlimited library." },
      { type: "tip", text: "Got a price list in a spreadsheet already? [Import it](/help/importing-your-price-list) instead of typing it in." },
    ],
    related: ["bundles", "importing-your-price-list", "building-a-quote", "markups-margins-and-vat"],
  },
  {
    slug: "bundles",
    title: "Bundles",
    summary: "Group services you always quote together, like a standard bathroom refit, and add them in one go.",
    category: "quotes",
    plan: "essentials",
    who: "Admins and Estimators",
    keywords: ["packages", "kits", "groups", "assemblies", "bathroom refit", "templates"],
    body: [
      { type: "p", text: "A bundle is a set of services from your library, each with its own quantity. Add the bundle to a quote and every service in it comes in as its own line, ready to adjust for the job in front of you." },
      { type: "h", text: "Making a bundle" },
      {
        type: "steps",
        items: [
          "Make sure the services you need are already in your [service library](/help/service-library).",
          "In **Service library**, click **New bundle**.",
          "Give it a **Name**, a **Category** and a **Unit** (it starts as 'job').",
          "Under **Services in this bundle**, choose a service and set the **Quantity**. Click **Add service** for each extra one.",
          "Check the **Bundle price** at the bottom, then click **Add bundle**.",
        ],
      },
      { type: "p", text: "For example, a 'Standard bathroom refit' bundle might hold strip out (1 job), first fix plumbing (1 job), tiling (12 m²) and a WC and basin fit (1 item)." },
      { type: "h", text: "How bundles behave" },
      {
        type: "list",
        items: [
          "The bundle price is the cost of its services added up, worked out for you. You don't type it in.",
          "When you change a service's rate, every bundle that contains it is repriced.",
          "On a quote, each service in the bundle becomes a separate line with its own quantity, rate and markup. Change the quantities if the job is bigger or smaller.",
          "A bundle can hold up to 50 services, and can't contain another bundle.",
          "If a service in a bundle is archived, the bundle page warns you so you can swap it out.",
        ],
      },
      { type: "h", text: "Good to know" },
      { type: "note", text: "Creating and editing bundles needs the Essentials plan or above." },
      { type: "tip", text: "Build bundles around the jobs you quote most. Two or three good ones can turn a 30 minute quote into a five minute one." },
    ],
    related: ["service-library", "building-a-quote", "importing-your-price-list"],
  },
  {
    slug: "importing-your-price-list",
    title: "Importing your price list",
    summary: "Bring your rates in from Excel or Google Sheets as a CSV file, with a check before anything is saved.",
    category: "quotes",
    who: "Admins and Estimators",
    keywords: ["import", "csv", "excel", "spreadsheet", "google sheets", "upload", "price list"],
    body: [
      { type: "p", text: "If your rates live in a spreadsheet, you can load them all into your service library at once. You'll see exactly what will happen before anything is saved." },
      { type: "h", text: "Step by step" },
      {
        type: "steps",
        items: [
          "Go to **Service library** and click **Import CSV**.",
          "Click **Download the template** if you want a ready made layout to fill in.",
          "Save your spreadsheet as a CSV file. In Excel use File, Save as, CSV. In Google Sheets use File, Download, CSV.",
          "Click **Choose a CSV file or drop it here** and pick your file.",
          "Check the list. Each row says **Will be added**, **Already in your library**, or what's wrong with it.",
          "Click **Import** to add the new services.",
        ],
      },
      { type: "h", text: "What the file needs" },
      {
        type: "list",
        items: [
          "A heading row first.",
          "**Required:** category, name, unit and rate (in pounds, before markup).",
          "**Optional:** description, and markup as a percentage. Leave markup blank to use your company default.",
          "Columns can be in any order, and common names like 'price', 'trade' or 'notes' are understood too. Any other columns are ignored.",
          "Up to 1,000 services per file, and the file must be under 1 MB.",
        ],
      },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Anything with the same category and name as a service already in your library is skipped, so it's safe to import the same file twice.",
          "Rows with problems are skipped too. Fix them in your spreadsheet and import again.",
          "On the Free plan the library holds up to 25 services. If your file has more than you have room for, nothing is imported and you'll be told how many will fit.",
        ],
      },
      { type: "tip", text: "Not sure your columns will match? Try a file with a handful of rows first and look at the check screen." },
    ],
    related: ["service-library", "bundles", "building-a-quote"],
  },
  {
    slug: "building-a-quote",
    title: "Building a quote",
    summary: "Start a quote for a client, add lines from your library or type your own, and watch the totals as you go.",
    category: "quotes",
    who: "Admins, the office and Estimators",
    keywords: ["new quote", "estimate", "lines", "sections", "pc sum", "provisional sum", "notes", "site address", "valid until"],
    body: [
      { type: "p", text: "A quote is built from sections (like 'Strip out' or 'Kitchen') and lines inside them. Everything saves as you type, so you can leave and come back to a draft whenever you like." },
      { type: "h", text: "Starting a quote" },
      {
        type: "steps",
        items: [
          "Go to **Quotes** and click **New quote**. You can also click **New quote** on a client's page.",
          "Choose the **Client**. Not listed? Click **Add a client**, then come back.",
          "Give it a **Title**, which is what the client sees at the top, for example 'Kitchen extension'.",
          "Click **Create quote**. It opens with one section called 'Works' and your company's default markup and VAT rate.",
        ],
      },
      { type: "h", text: "Adding lines" },
      { type: "p", text: "In the add row at the bottom of a section, start typing. Matches from your [service library](/help/service-library) and [bundles](/help/bundles) appear as you type: use the arrow keys and Enter, or click one. If nothing fits, press Enter to add what you typed as a custom line." },
      { type: "p", text: "Click any cell to change the **Item**, **Qty**, **Unit**, **Rate** or **Markup**. Press Enter to save a cell, Esc to cancel your change, and the up and down arrows to move between rows like a spreadsheet." },
      { type: "h", text: "Notes, PC sums and provisional sums" },
      {
        type: "list",
        items: [
          "Click the note icon on a line to add a note, such as what's included or excluded. Tick **Show the note to the client** if they should see it.",
          "In the same place, set the **Type** to **PC sum** or **Provisional sum** for allowances you'll adjust to the actual cost later. The client sees a label on those lines.",
          "Use the menu on a line or section to move it up or down, or delete it. Click **Add section** to add another.",
        ],
      },
      { type: "h", text: "The Details tab" },
      { type: "p", text: "Here you can change the title and client, set a **Valid until** date (leave it blank for no expiry), change the **Default markup** and **VAT rate**, and add a **Site address** if the work isn't at the client's own address. You can also delete a draft that has never been sent." },
      { type: "h", text: "Keeping an eye on the numbers" },
      { type: "p", text: "The panel on the right shows cost, markup, subtotal, VAT, the total and your gross margin, plus a total for each section. Only your team sees costs and margins. See [Markups, margins and VAT](/help/markups-margins-and-vat)." },
      { type: "tip", text: "On Essentials and Pro, set out how the client will pay in the **Payment plan** tab, for example a deposit and stage payments. See [Payment plans](/help/payment-plans)." },
    ],
    related: ["service-library", "markups-margins-and-vat", "sending-a-quote", "payment-plans", "clients"],
  },
  {
    slug: "markups-margins-and-vat",
    title: "Markups, margins and VAT",
    summary: "How your rates, markup and VAT add up to the price the client sees, and what stays private.",
    category: "quotes",
    who: "Admins, the office and Estimators see costs and margins",
    keywords: ["markup", "margin", "profit", "vat", "reduced rate", "zero rated", "default markup", "cost"],
    body: [
      { type: "p", text: "In Builder OS every rate you enter is your cost, and markup is added on top to give the client's price. Clients only ever see the final price, never your cost or your markup." },
      { type: "h", text: "How a line is priced" },
      { type: "p", text: "The client's unit price is your rate plus the markup, rounded to the penny. The line total is the quantity times that unit price. For example, a skim at £14.50 per m² with 15% markup is £16.68 per m² to the client, so 20 m² is £333.60 before VAT." },
      { type: "h", text: "Where markup comes from" },
      {
        type: "list",
        items: [
          "Your company default, set under **Quote defaults** in [Settings](/app/settings). New quotes start with it.",
          "A service's own markup in the library, if you set one. It's used whenever that service is added to a quote.",
          "The quote's **Default markup** on the **Details** tab. This is used for new lines only. Lines already on the quote keep their own markup.",
          "Each line's **Markup** cell, which you can change at any time while the quote is a draft.",
        ],
      },
      { type: "h", text: "Margin" },
      { type: "p", text: "The summary panel shows **Cost**, **Markup**, **Subtotal**, VAT and **Total**, plus your **Gross margin**: the markup as a share of the price before VAT. Markup and margin are not the same. A 25% markup gives a 20% margin." },
      { type: "h", text: "VAT" },
      {
        type: "list",
        items: [
          "Each quote has one VAT rate: 20% (standard), 5% (reduced) or 0% (zero-rated). Pick it on the **Details** tab.",
          "New quotes start with your **Default VAT rate** from Settings.",
          "VAT is worked out on the subtotal and shown as its own line to the client.",
          "Add your VAT number in Settings so it appears on your invoices. Leave it blank if you're not VAT registered.",
        ],
      },
      { type: "note", text: "Site leads and employees never see costs, markups or margins anywhere in Builder OS." },
      { type: "tip", text: "Check your VAT position with your accountant. Some work, like certain new builds or energy saving installs, can be zero-rated or reduced." },
    ],
    related: ["building-a-quote", "service-library", "company-settings"],
  },
  {
    slug: "sending-a-quote",
    title: "Sending a quote",
    summary: "Send your quote by email or as a link, and see when your client opens it.",
    category: "quotes",
    who: "Admins, the office and Estimators",
    keywords: ["send", "email", "link", "share", "viewed", "opened", "status", "free plan limit"],
    body: [
      { type: "p", text: "When the quote is ready, send it. Your client gets their own private page where they can read it, ask questions and accept it with a signature." },
      { type: "h", text: "Step by step" },
      {
        type: "steps",
        items: [
          "Open the draft and click **Send quote** at the top.",
          "Leave **Email the link to** ticked to email it to your client, or untick it to send the link yourself.",
          "Add a **Message** if you like, such as 'Hi Sarah, here's the quote we talked about.'",
          "Click **Send quote**.",
          "You'll see the client's link. Click **Copy link** to paste it into a text or WhatsApp, or **Open in your email app** if it wasn't emailed.",
        ],
      },
      { type: "p", text: "The email comes from your company name, shows the quote number and total including VAT, and replies go straight to you." },
      { type: "h", text: "After you send" },
      {
        type: "list",
        items: [
          "The quote is locked, so the client sees exactly what you sent. To change it, [revise it](/help/revising-a-quote).",
          "The status moves from **Sent** to **Viewed** the first time they open it. You'll see how many times it's been opened, and get a notification and an email the first time.",
          "**Preview as client** shows you their view. Your previews don't count as opens.",
          "**Copy client link** gets the link again at any time.",
        ],
      },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "A quote needs at least one line before you can send it.",
          "If your client has no email address, you'll get a link to send yourself.",
          "If you haven't set a payment plan, the quote shows a single 'Payment on completion'.",
          "On the Free plan you can send 3 new quotes a month. Sending an updated version of a quote doesn't count. Essentials and Pro are unlimited.",
          "On Essentials and Pro, quotes carry your logo and brand colour from Settings.",
        ],
      },
      { type: "tip", text: "The link is your client's [portal](/help/client-portal): every quote you send them appears in the same place." },
    ],
    related: ["client-portal", "revising-a-quote", "accepted-quotes-and-signatures", "client-comments-and-questions"],
  },
  {
    slug: "revising-a-quote",
    title: "Revising a sent quote",
    summary: "Make changes after sending, then send the update as a new version. The client sees the old one until then.",
    category: "quotes",
    who: "Admins, the office and Estimators",
    keywords: ["revise", "edit sent quote", "change", "update", "new version", "declined", "expired"],
    body: [
      { type: "p", text: "Once a quote is sent it's locked, so there's always a clear record of what your client saw. If something changes, say they want a different worktop, you revise it and send an updated version." },
      { type: "h", text: "Step by step" },
      {
        type: "steps",
        items: [
          "Open the sent quote and click **Revise**.",
          "Click **Revise quote** to confirm. The quote reopens as a draft.",
          "Make your changes. A yellow banner reminds you that the client still sees the last version.",
          "Click **Send update**, add a message if you like, and send it.",
        ],
      },
      { type: "h", text: "What your client sees" },
      {
        type: "list",
        items: [
          "While you're revising, they still see the last version you sent, with a note that you're updating it. They can't accept it until the new version arrives.",
          "The updated quote shows its version number, for example 'version 2', and the email says 'Updated quote'.",
          "Their comments and questions stay with the quote, across all versions.",
        ],
      },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "You can revise a quote that's been sent, viewed, declined or has passed its valid until date. A declined quote is often worth a second go at a different price.",
          "Accepted quotes are final and can't be revised. For changes once the job's agreed, use [variations](/help/variations).",
          "Sending an update doesn't count towards the Free plan's 3 new quotes a month.",
          "A quote that has ever been sent can't be deleted. It's kept as a record.",
        ],
      },
      { type: "tip", text: "If a quote has expired, revise it, set a new **Valid until** date on the **Details** tab and send the update." },
    ],
    related: ["sending-a-quote", "accepted-quotes-and-signatures", "variations", "duplicating-quotes"],
  },
  {
    slug: "accepted-quotes-and-signatures",
    title: "Accepted quotes and signatures",
    summary: "How clients accept or decline online, what's recorded when they sign, and what to do next.",
    category: "quotes",
    keywords: ["accept", "sign", "signature", "e-signature", "declined", "won", "contract", "evidence"],
    body: [
      { type: "p", text: "Your client accepts a quote online by typing their name as a signature. No printing, scanning or chasing paper, and you get a clear record of exactly what they agreed to." },
      { type: "h", text: "How your client accepts" },
      {
        type: "steps",
        items: [
          "They open the quote from their email or link and click **Accept & sign**.",
          "They type their full name and their signature, and tick to confirm that typing their name is their electronic signature.",
          "They click **Sign and accept**.",
        ],
      },
      { type: "p", text: "If they'd rather not go ahead, they click **Decline** and can give a reason. A reason is optional." },
      { type: "h", text: "What's recorded" },
      { type: "p", text: "On the quote you'll see an **Accepted** card with their signature, name, the time, the IP address they signed from and a reference for the exact version they signed. The client sees the same signature on their copy." },
      { type: "h", text: "You'll be told" },
      { type: "p", text: "Whoever sent the quote gets a notification and an email when the client accepts or declines (or the Admins, if that person has left). A declined quote shows their reason, and you can [revise it](/help/revising-a-quote) and send an update." },
      { type: "h", text: "When they can't accept" },
      {
        type: "list",
        items: [
          "While you're revising the quote. They can accept the new version once you send it.",
          "After the **Valid until** date. They're asked to leave a comment for an updated quote.",
          "Once they've already accepted or declined that version.",
        ],
      },
      { type: "h", text: "What next" },
      {
        type: "list",
        items: [
          "Accepted quotes are final. Changes from here on are [variations](/help/variations).",
          "Raise invoices from the payment schedule on the quote. See [Raising invoices](/help/raising-invoices).",
          "On Pro, click **Start project** to turn the quote into a project.",
        ],
      },
    ],
    related: ["sending-a-quote", "variations", "raising-invoices", "projects"],
  },
  {
    slug: "duplicating-quotes",
    title: "Duplicating a quote",
    summary: "Copy any quote into a new draft for the same client, to save time on similar jobs.",
    category: "quotes",
    who: "Admins, the office and Estimators",
    keywords: ["copy", "duplicate", "clone", "template", "reuse", "similar job"],
    body: [
      { type: "p", text: "Duplicating copies a quote into a brand new draft. It's handy when you want to offer a client two options, like a basic and a premium bathroom, or start from something close to what you need." },
      { type: "h", text: "Step by step" },
      {
        type: "steps",
        items: [
          "Open the quote you want to copy. It can be a draft, sent, accepted or declined.",
          "Click **Duplicate**.",
          "The copy opens straight away as a draft called the same name with '(copy)' on the end. Rename it on the **Details** tab.",
        ],
      },
      { type: "h", text: "What's copied" },
      {
        type: "list",
        items: [
          "Every section and line, with the same quantities, rates, markups, notes and line types.",
          "The site address, the default markup, the VAT rate and the payment plan.",
          "The same client. To quote a different client, change the **Client** on the **Details** tab.",
        ],
      },
      { type: "p", text: "The valid until date, comments and signatures are not copied. The copy has its own quote number and nothing has been sent." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Rates are copied as they were on the original quote. If you've changed prices in your library since, update the lines on the copy.",
          "If you duplicate a draft you're editing, your latest changes are saved first so the copy includes them.",
          "You can't duplicate a quote for an archived client. Restore the client first.",
        ],
      },
      { type: "tip", text: "Keep a tidy 'master' quote for jobs you price often, and duplicate it whenever a similar enquiry comes in." },
    ],
    related: ["building-a-quote", "bundles", "revising-a-quote"],
  },
];
