/** The help centre article for each getting-started step (src/core/onboarding.ts). */
export const STEP_GUIDES: Record<string, string> = {
  tour: "finding-your-way-around",
  company_details: "setting-up-your-company",
  logo: "setting-up-your-company",
  bank_details: "bank-details-and-payment-terms",
  team: "logins-and-roles",
  library: "service-library",
  bundle: "bundles",
  quote_created: "building-a-quote",
  quote_sent: "sending-a-quote",
  quote_accepted: "accepted-quotes-and-signatures",
  payment_plan: "payment-plans",
  invoice: "raising-invoices",
  online_payments: "taking-payments-online",
  project: "projects",
  site_app: "site-app",
  variation: "variations",
  costs: "expenses-and-receipts",
  lead: "leads",
  enquiry_form: "web-enquiry-form",
  online_booking: "online-survey-booking",
  automation: "automations",
};
