import type { HelpArticle } from "./types";

export const TEAM_ARTICLES: HelpArticle[] = [
  {
    slug: "team-and-workers",
    title: "Your team: employees and subcontractors",
    summary: "Keep everyone who works for you in one list, with or without a login, and give them tasks on jobs.",
    category: "team",
    plan: "pro",
    who: "Admins and the office can add and change people. Estimators and site leads can view.",
    keywords: ["team", "workers", "staff", "subcontractor", "labourer", "add person", "day rate", "emergency contact", "left"],
    body: [
      { type: "p", text: "The Team page is a list of everyone who works for you: employees, labourers and subcontractors. They don't need a login to be on it, so you can give tasks to your regular plasterer even if they'll never open the app." },
      { type: "h", text: "Adding someone" },
      {
        type: "steps",
        items: [
          "Go to [Team](/app/team) and click **Add person**.",
          "Enter their **Name**. That's the only thing you need.",
          "Choose whether they work as an **Employee** or a **Subcontractor**, and add their **Trade** (for example Carpenter or Labourer).",
          "Fill in their **Mobile**, **Email**, the date they **Started**, an **Emergency contact** and **Emergency phone** if you have them.",
          "Click **Add to the team**. You can add the rest later.",
        ],
      },
      { type: "h", text: "What the People list shows" },
      {
        type: "list",
        items: [
          "Name, trade and phone number (tap to ring).",
          "**Site app**: their role if they have a login, or No login.",
          "**Open tasks**: how many unfinished tasks they have.",
          "**On site** if they're checked in right now, and **Cert expired** or **Cert expiring** if a certificate needs attention.",
        ],
      },
      { type: "p", text: "Click a name to open their page: details, certificates, site app login, what they're working on and their recent hours on site." },
      { type: "h", text: "Day rate" },
      { type: "p", text: "**Day rate (cost)** is what someone costs you per day. It's used to work out labour costs on a job from their check-in hours. Only people who can see costs (Admins, the office and estimators) can see or change it." },
      { type: "h", text: "When someone leaves" },
      { type: "p", text: "Open their page and click **Mark as left**. Their history stays, but any unfinished tasks are unassigned so nothing falls through the cracks. If they were still checked in, they're checked out. To see people who've left, click **Show people who've left** under the list, and use **Bring back to the team** if they return." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Anyone you invite to Builder OS is added to the team automatically. If you've already added them with the same email, their login links to that person.",
          "Use the **Trade** box on a task for a firm that isn't on your team, such as a roofing contractor.",
        ],
      },
    ],
    related: ["logins-and-roles", "certificates", "weekly-schedule", "project-stages-and-tasks"],
  },
  {
    slug: "certificates",
    title: "Certificates and cards",
    summary: "Record CSCS cards, Gas Safe, insurance and the like, and get a reminder before any of them run out.",
    category: "team",
    plan: "pro",
    who: "Admins and the office can add and change certificates",
    keywords: ["certificate", "CSCS", "Gas Safe", "NICEIC", "first aid", "insurance", "expiry", "renewal", "tickets", "cards", "IPAF", "PASMA"],
    body: [
      { type: "p", text: "Keep track of everyone's cards, tickets and registrations in one place. Builder OS tells you before one expires, so nobody turns up on site with an out-of-date CSCS card or lapsed insurance." },
      { type: "h", text: "Adding a certificate" },
      {
        type: "steps",
        items: [
          "Go to [Team](/app/team) and click the person's name.",
          "Under **Certificates and cards**, click **Add certificate**.",
          "Type the name. Suggestions pop up as you type, such as CSCS card, Gas Safe registration, 18th Edition (BS 7671), SMSTS, First aid at work, IPAF or Public liability insurance. Any name is fine.",
          "Add the card or registration number if you like.",
          "Set the expiry date, then click **Save**.",
        ],
      },
      { type: "h", text: "How each certificate is marked" },
      {
        type: "list",
        items: [
          "**Valid**: more than 30 days to go.",
          "**Expires soon**: expires in the next 30 days.",
          "**Expired**: the date has passed.",
          "**No expiry**: no date was entered.",
        ],
      },
      { type: "h", text: "Reminders" },
      { type: "p", text: "When a certificate is 30 days from expiring (or has already expired), Admins and the office get an email listing it, plus a notification in the app. Each certificate is mentioned once, so you won't be nagged every day." },
      { type: "p", text: "Expired and expiring certificates also show in a box at the top of the Team page and on your dashboard, and the person gets a **Cert expired** or **Cert expiring** label in the People list." },
      { type: "h", text: "Renewing" },
      { type: "p", text: "When someone renews a card, click the pencil next to it, change the expiry date and click **Save**. With a new date, the reminder can go out again next time it's due." },
      { type: "tip", text: "Add public liability insurance for each subcontractor with its renewal date. It's an easy one to forget, and you'll know before it lapses." },
    ],
    related: ["team-and-workers", "notifications"],
  },
  {
    slug: "weekly-schedule",
    title: "The week's plan: who's where",
    summary: "See every person's jobs for the week, built from the dates on their project tasks.",
    category: "team",
    plan: "pro",
    who: "Admins, the office, estimators and site leads",
    keywords: ["schedule", "rota", "planner", "this week", "who's where", "allocation", "diary"],
    body: [
      { type: "p", text: "The week's plan shows who's working on which job each day. It's handy on a Friday afternoon for sorting out next week, or first thing on Monday to check everyone knows where they're going." },
      { type: "h", text: "Opening it" },
      { type: "p", text: "Go to [Team](/app/team) and click **This week**. Each row is a person and each column a day, Monday to Sunday, with today highlighted." },
      { type: "h", text: "How it's built" },
      { type: "p", text: "You don't fill in the plan separately. It comes from task dates on your current projects (booked in, on site, snagging or on hold). When a task has a person and a start or due date, it shows on their row for those days." },
      {
        type: "steps",
        items: [
          "Open a project and go to the **List**, **Board** or **Timeline** tab.",
          "Click a task, choose **Who's doing it**, and set the **Start** and **Due** dates.",
          "Save. The task now appears on that person's row in the week's plan.",
        ],
      },
      { type: "h", text: "Reading the plan" },
      {
        type: "list",
        items: [
          "Each box shows the job's name and the task (or how many tasks, if there are several on the same job that day).",
          "The dot shows how it's going: grey for to do, blue for in progress, amber for waiting, green for done.",
          "Hover over a box to see the task names, and click it to open that project's timeline.",
          "Use the arrows to move to the previous or next week, and **This week** to jump back.",
        ],
      },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Tasks without dates aren't on the plan. Give them dates on the project's timeline.",
          "Completed projects drop off the plan.",
          "People who've left aren't shown.",
        ],
      },
      { type: "tip", text: "If a row is empty for a day, that person has nothing dated. It's a quick way to spot who's free to help out on another job." },
    ],
    related: ["project-board-and-timeline", "project-stages-and-tasks", "team-and-workers", "calendar"],
  },
  {
    slug: "timesheets-and-check-ins",
    title: "Timesheets and check-ins",
    summary: "Your team checks in and out of site on their phone, and their hours build up into weekly timesheets.",
    category: "team",
    plan: "pro",
    who: "Admins, the office, estimators and site leads can see timesheets",
    keywords: ["timesheet", "hours", "check in", "check out", "clock in", "attendance", "labour", "time on site"],
    body: [
      { type: "p", text: "Instead of collecting paper timesheets on a Friday, your team checks in when they arrive on site and checks out when they leave. Builder OS adds up the hours for you." },
      { type: "h", text: "Checking in and out" },
      { type: "p", text: "In the [site app](/help/site-app), people with a login see a check-in box at the top of their Today screen and on each job. They choose the job, tap **Check in**, then tap **Check out** when they leave." },
      {
        type: "list",
        items: [
          "The time is recorded when they tap, so they can't type in a different one.",
          "If they allow it, their phone's location is saved with the time. Click **In** or **Out** next to a visit to see it on a map.",
          "Checked in at one job and tap **Check in here instead** on another? The first visit is closed and a new one starts.",
          "They can only check in to jobs they're working on (they have a task there, or they run it).",
        ],
      },
      { type: "h", text: "Reading the timesheets" },
      { type: "p", text: "Go to [Team](/app/team) and click **Timesheets**. You'll see:" },
      {
        type: "list",
        items: [
          "A table of hours per person for each day of the week, with a total for the week and a total row along the bottom.",
          "**on site now** next to anyone who's checked in at the moment.",
          "A **Check-ins** list underneath: day, person, job, time in and out, where they checked in and out, and how long.",
        ],
      },
      { type: "p", text: "Use the arrows to move between weeks. Hours count on the day the person checked in. Each person's page also shows their hours for the last 7 days and last 4 weeks." },
      { type: "h", text: "Hours and job costs" },
      { type: "p", text: "If a person has a day rate, their time on site is costed against the job (a day rate covers 8 hours). You'll see it in the job's costs. See [Job costing reports](/help/job-costing-reports)." },
      { type: "h", text: "Correcting times" },
      { type: "p", text: "Someone forgot to check out, or their phone died? Admins and the office can fix it." },
      {
        type: "steps",
        items: [
          "Find the visit in the **Check-ins** list, or on the person's page.",
          "Click the pencil next to the times.",
          "Change the day, the time they arrived and the time they left, then click **Save times**.",
        ],
      },
      {
        type: "list",
        items: [
          "Times are in UK time. A leaving time earlier than the arrival counts as the next morning, for night work.",
          "A visit can't be in the future, longer than 16 hours, or overlap another of their visits.",
          "Corrected visits show an **edited** tag. Hover over it to see who changed it and when.",
          "A **no signal** tag means the person checked in or out with no signal and the phone sent it later. The time is when they tapped.",
          "If someone's still checked in, you can leave the leaving time empty to keep them on site, or fill it in to check them out.",
        ],
      },
      { type: "note", text: "If someone forgets to check out, their visit keeps counting until they do, or until you correct it. Remind the team to tap **Check out** before they leave site." },
      { type: "tip", text: "Your subcontractors and labourers need a login to check in. See [Logins and roles](/help/logins-and-roles)." },
    ],
    related: ["site-app", "team-and-workers", "job-costing-reports", "logins-and-roles", "working-offline"],
  },
  {
    slug: "site-app",
    title: "The site app",
    summary: "A simple phone app for your team: today's tasks, their jobs, check in and out, site updates and receipts.",
    category: "team",
    plan: "pro",
    who: "Everyone with a login. Employees use only the site app.",
    keywords: ["mobile", "phone", "site app", "employee app", "today", "tasks", "photos", "receipts", "surveys", "directions"],
    body: [
      { type: "p", text: "The site app is Builder OS made for phones, with big buttons you can use with gloves on. Your team sees just their own jobs and tasks, never prices or margins." },
      { type: "h", text: "Getting in" },
      { type: "p", text: "Anyone with the **Employee** role goes straight to the site app when they sign in. Everyone else can open it from **Site app** in the sidebar, and get back with the **Office** button. The person needs to be on your team list and linked to their login, or they'll see \"You're not on the team list\". See [Logins and roles](/help/logins-and-roles)." },
      { type: "tip", text: "On a phone, add the site app to the home screen from the browser's menu. It then opens like any other app." },
      { type: "p", text: "No signal on site? The site app keeps working and sends everything when you're back online. See [Using the site app with no signal](/help/working-offline)." },
      { type: "h", text: "The Today screen" },
      {
        type: "list",
        items: [
          "**Check in** and **Check out** for their jobs. See [Timesheets and check-ins](/help/timesheets-and-check-ins).",
          "**Surveys**: any survey visits booked for them today or tomorrow, with directions and the client's number.",
          "**Today**: tasks on today, late, under way or waiting, and anything finished today.",
          "**Coming up**: the rest of their tasks.",
          "**My jobs**: every current job they have a task on, or run.",
        ],
      },
      { type: "h", text: "Updating tasks" },
      { type: "p", text: "Tap the box next to a task to mark it done. Tap the start button to mark it in progress, or the waiting button to say what it's waiting for (for example \"plasterboard delivery\"). The reason is added to the task's notes with the date, so the office sees it straight away." },
      { type: "h", text: "On a job" },
      { type: "p", text: "Tap a job to see:" },
      {
        type: "list",
        items: [
          "The site address with a **Directions** button, and a button to call the client.",
          "**My tasks here**.",
          "**Post an update**: a note and photos that go into the job's [site diary](/help/site-diary). Updates are team only until the office shares them with the client.",
          "**Receipts**: tap **Add a receipt**, take a **Photo of the receipt**, fill in what it was for, the shop and the total, then **Save receipt**. Tick **Bought for the client** if they'll pay it back. It goes into the job's costs and the office gets a notification. See [Expenses and receipts](/help/expenses-and-receipts).",
          "**Latest from site**: recent diary entries for the job.",
        ],
      },
      { type: "note", text: "The site app is part of the Pro plan. On other plans, the team sees a message asking the office to upgrade." },
    ],
    related: ["timesheets-and-check-ins", "logins-and-roles", "site-diary", "expenses-and-receipts", "reading-receipts"],
  },
  {
    slug: "logins-and-roles",
    title: "Logins and roles",
    summary: "Invite your office and site staff, and choose what each person can see and do with their role.",
    category: "team",
    who: "Admins invite people and change roles",
    keywords: ["invite", "login", "user", "role", "permissions", "admin", "office", "estimator", "site lead", "employee", "access"],
    body: [
      { type: "p", text: "Each person who signs in to Builder OS has a role. The role decides what they can see and change, so your site team never sees your margins and only Admins can change company settings." },
      { type: "h", text: "The five roles" },
      {
        type: "list",
        items: [
          "**Admin**: everything, including company settings, team and billing.",
          "**Office**: clients, quotes, invoices and payments. No company settings.",
          "**Estimator**: builds and sends quotes, and looks after the service library.",
          "**Site lead**: runs jobs on site: projects, tasks, photos and variations. No prices or margins.",
          "**Employee**: the site app only: today's site, tasks, check-in and photos.",
        ],
      },
      { type: "h", text: "Inviting someone" },
      {
        type: "steps",
        items: [
          "Go to [Settings, Team](/app/settings/team).",
          "Click **Invite** and enter their email address.",
          "Choose their role and send the invitation.",
          "They get an email, set up their login, and land in the right place: the office app, or the site app for Employees.",
        ],
      },
      { type: "p", text: "You can change someone's role or remove them from the same page. Only Admins can invite people or change roles. Everyone else can see who's in the company and is asked to speak to an Admin." },
      { type: "note", text: "The Free plan includes one login, for the company's Admin. Anyone else you invite can accept, but sees a page asking them to speak to you until you [choose a plan](/help/plans-and-pricing). Trials, Essentials and Pro have no limit on logins." },
      { type: "h", text: "Logins and the team list" },
      { type: "p", text: "When someone joins, they're added to your [Team](/help/team-and-workers) list automatically. If you've already added them on the Team page with the same email, the two link up. If they don't, open the person on the Team page and use **Link to an existing login** under **Site app**." },
      { type: "h", text: "Good to know" },
      {
        type: "list",
        items: [
          "Plans are priced per company, not per person, so adding your site crew doesn't cost extra.",
          "People on your team list don't need a login. You can still give them tasks, and the office sees everything.",
          "Removing someone's login doesn't remove them from the Team list. Use **Mark as left** on their Team page for that.",
        ],
      },
      { type: "tip", text: "Give your foreman the Site lead role. They can run jobs, post updates and manage tasks without seeing what you're charging." },
    ],
    related: ["team-and-workers", "site-app", "plans-and-pricing", "company-settings"],
  },
  {
    slug: "working-offline",
    title: "Using the site app with no signal",
    summary: "The site app keeps working in basements and new builds. What you do is saved on the phone and sent later.",
    category: "team",
    plan: "pro",
    who: "Everyone who uses the site app",
    keywords: ["offline", "no signal", "no internet", "no reception", "basement", "sync", "waiting to send", "data"],
    body: [
      { type: "p", text: "Plenty of sites have no signal: basements, new builds, the countryside. The site app keeps working anyway. Your jobs and tasks stay on your phone, and anything you do is saved there until you're back online." },
      { type: "h", text: "Getting ready" },
      { type: "p", text: "Open the site app's Today screen once while you have signal (on Wi-Fi at home is fine). It saves Today and every one of your jobs on the phone, so they open later even with no signal. Adding the site app to your home screen helps too: see [The site app](/help/site-app)." },
      { type: "h", text: "What works with no signal" },
      {
        type: "list",
        items: [
          "**Check in and check out.** The time is the moment you tap, not when it's sent. The office sees a **no signal** tag next to the visit so they know.",
          "**Ticking off tasks**, starting them, or saying what they're waiting for.",
          "**Site updates with photos.** The photos are shrunk and kept on the phone until they can go.",
          "**Receipts with photos.** Reading the receipt automatically needs signal, so type the total in yourself.",
        ],
      },
      { type: "p", text: "A dark bar at the top says when you have no signal and how many changes are waiting to send." },
      { type: "h", text: "When the signal comes back" },
      { type: "p", text: "Everything waiting is sent by itself, in the order you did it, as soon as the phone is back online. You can also tap the arrows on the bar to send now. If something can't be sent (for example the job was closed in the office), a red note says what and why. Tap the cross to clear it once you've told the office." },
      { type: "note", text: "Changes are kept on the phone for up to a week. Something saved longer ago than that won't be sent, so open the app when you're back in signal. Don't clear the browser's data while changes are waiting." },
      { type: "tip", text: "If a phone is shared, sign out when you're done. The next person to sign in on it won't see your saved jobs." },
    ],
    related: ["site-app", "timesheets-and-check-ins"],
  },
];
